In [1]:
import numpy as np
x = np.random.random((3, 3, 3))
print(x)

[[[0.70198418 0.93138574 0.25270598]
  [0.33295434 0.72731555 0.97914441]
  [0.67044705 0.50258806 0.90668386]]

 [[0.85867951 0.64947931 0.34972952]
  [0.84958913 0.16753572 0.02523477]
  [0.04641182 0.43138531 0.61066924]]

 [[0.69646557 0.03272717 0.9901317 ]
  [0.68983559 0.28142219 0.96998848]
  [0.97718308 0.64752501 0.14796498]]]
